from fastapi import APIRouter, Depends, HTTPException, Query, status

from app.api.deps import get_optional_user
from app.models.auth import UserProfile
from app.models.battleground import (
    HintRequest,
    HintResponse,
    QuestionDetail,
    QuestionSummary,
    RunCodeRequest,
    RunCodeResponse,
    SolutionRequest,
    SolutionResponse,
    SubmitResponse,
    UserProgressResponse,
)
from app.services.battleground import battleground_service

router = APIRouter()


@router.get(
    "/questions",
    response_model=list[QuestionSummary],
    summary="List top 50 SQL Battleground questions",
)
def list_questions(
    difficulty: str | None = Query(default=None, description="Filter by Easy, Medium, or Hard"),
    category: str | None = Query(default=None, description="Filter by study plan track"),
    search: str | None = Query(default=None, description="Search keyword in title or description"),
    current_user: UserProfile | None = Depends(get_optional_user),
) -> list[QuestionSummary]:
    user_id = current_user.id if current_user else None
    return battleground_service.list_questions(
        user_id=user_id,
        difficulty=difficulty,
        category=category,
        search=search,
    )


@router.get(
    "/questions/{question_id}",
    response_model=QuestionDetail,
    summary="Get problem description, starter code, and efficiency tips",
)
def get_question(
    question_id: str,
    current_user: UserProfile | None = Depends(get_optional_user),
) -> QuestionDetail:
    user_id = current_user.id if current_user else None
    q = battleground_service.get_question(question_id, user_id=user_id)
    if not q:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Question with id '{question_id}' not found.",
        )
    return q


@router.post(
    "/run",
    response_model=RunCodeResponse,
    summary="Execute SQL against real database and compare with expected output",
)
def run_code(
    request: RunCodeRequest,
) -> RunCodeResponse:
    return battleground_service.run_code(request.question_id, request.sql)


@router.post(
    "/submit",
    response_model=SubmitResponse,
    summary="Submit final SQL solution, validate test cases, and record progress",
)
def submit_code(
    request: RunCodeRequest,
    current_user: UserProfile | None = Depends(get_optional_user),
) -> SubmitResponse:
    user_id = current_user.id if current_user else None
    return battleground_service.submit_code(request.question_id, request.sql, user_id=user_id)


@router.post(
    "/hint",
    response_model=HintResponse,
    summary="Get dynamic Groq AI code critique, guided hint, and efficiency tips",
)
def get_hint(
    request: HintRequest,
) -> HintResponse:
    return battleground_service.get_hint(
        request.question_id, request.user_sql, request.error_message
    )


@router.post(
    "/solution",
    response_model=SolutionResponse,
    summary="Get optimal solution, step-by-step walkthrough, and efficiency breakdown generated by Groq",
)
def get_solution(
    request: SolutionRequest,
) -> SolutionResponse:
    try:
        return battleground_service.get_solution(request.question_id, request.user_sql)
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(exc),
        ) from exc


@router.get(
    "/progress",
    response_model=UserProgressResponse,
    summary="Get learner's solved battleground challenge progress",
)
def get_progress(
    current_user: UserProfile | None = Depends(get_optional_user),
) -> UserProgressResponse:
    user_id = current_user.id if current_user else None
    return battleground_service.get_user_progress(user_id=user_id)
